### ISSUE TITLE
Add Unit Tests to devel-meet-reqs

### ISSUE THREAD

**Issue by PhillSimonds** [networktocode/schema-enforcer#30]
As code has been largely modified by the `devel-meet-reqs` branch, unit tests need to be rewritten to provide full coverage of the code.

## Tasks:

- [x] Add coverage to `invoke pytest` command and make it so it's not installing poetry with every run.
- [x] Unit tests for config.py
- [x] Unit tests for instances/file.py
- [x] Unit tests for schemas/jsonschema.py -- @PhillSimonds 
- [x] Unit tests for schemas/manager.py -- @armartirosyan 
- [x] Unit tests for ansible_inventory.py -- @armartirosyan 
- [ ] Unit tests for cli.py --
- [ ] Unit tests for utils.py
- [ ] Unit tests for validation.py
- [ ] Update unit tests on ansible.py -- @PhillSimonds
